<?php

namespace JulienIts\EmailsQueueBundle\Repository;

/**
 * EmailSentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailSentRepository extends \Doctrine\ORM\EntityRepository
{
}
